---
AWSTemplateFormatVersion: "2010-09-09"
Description: conductor

Parameters:

  GHO:
    Type: String
    Description: This is the root organization where repos are stored (Case Sensitive)
    Default: "grolston"

  RN:
    Type: String
    Description: The repo(s) these roles will have access to. (Use * for all Org Repos or wildcard)
    Default: "*"

  BH:
    Type: String
    Description: Name of the git branch to to trust. (Use * for all branches)
    Default: "main"
    
  RoleName:
    Type: String
    Description: Name the Role
    Default: "conductor"

Resources:

  IdpGitHubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
        - !Sub https://github.com/${GHO}/${RN}
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Tags:
      - Key: Name
        Value: !Sub ${RoleName}-OIDC-Provider

  WorkshopAdmin:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ${RoleName}
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If
                - CreateProvider
                - !Ref IdpGitHubOidc
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: "sts.amazonaws.com"
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GHO}/${RN}:ref:refs/heads/${BH}
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess
