---
AWSTemplateFormatVersion: "2010-09-09"
Description: conductor

Parameters:

  GHO:
    Type: String
    Description: case sensitive
    Default: "grolston"

  RN:
    Type: String
    Description: case sensitive
    Default: "c2"

  BH:
    Type: String
    Description: case sensitive
    Default: "main"
    
  RoleName:
    Type: String
    Description: Name the Role
    Default: "conductor"

Resources:

  IdpGitHubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
        - !Sub https://github.com/${GHO}/${RN}
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Tags:
      - Key: Name
        Value: !Sub ${RoleName}-OIDC-Provider

  WorkshopAdmin:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref IdpGitHubOidc
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: "sts.amazonaws.com"
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GHO}/${RN}:ref:refs/heads/${BH}
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess
Outputs:
     oWorkshopAdminArn:
      Description: Workshop Admin Arn
      Value: !GetAtt WorkshopAdmin.Arn
